--[[
    Fluent Interface Suite
    This script was generated by ci/bundle.lua, and is not intended to be modified.
    To view the source code, see the 'src' folder on GitHub!

    Author: dawid
    License: MIT
    GitHub: https://github.com/dawid-scripts/Fluent
--]]
